name: Python Django Exercise CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: 'development'
    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ vars.DB_HOST }}
        DB_PORT: ${{ vars.DB_PORT }}

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Run tests
      run: docker-compose run web python manage.py test
